
/* 
*	SPDX-License-Identifier:	BSD-3-Clause 
* The above license addresses copyright obligations. Please refer to Section 10.4 of the 
* ATIS Operating Procedures for information about patent licensing obligations under 
* ATIS' Intellectual Property Rights Policy.
*/

// This file is automatically generated by the script cdt/cxxhelper.py
// If changes are required they should be created by running this script and 
// not by manually editing this file

#include "cdt/CDT-container.hxx"
#include "cdt/CDT-commonTypes.hxx"
#include "cdt/CDT-AE.hxx"
#include "cdt/HD-act-toggle.hxx"
#include "cdt/CDT-notification.hxx"
#include "cdt/CDT-subscription.hxx"
#include "cdt/HD-deviceLight.hxx"
#include "cdt/CDT-enumerationTypes.hxx"
#include "cdt/HD-mod-binarySwitch.hxx"
#include "cdt/CDT-accessControlPolicy.hxx"
#include "cdt/CDT-CSEBase.hxx"
#include "cdt/CDT-pollingChannel.hxx"
#include "cdt/CDT-contentInstance.hxx"
