/**
 * RandomMeterValue Header File: RandomMeterValue.h
 * 
 * This file is used to generate random values for use in 
 * simulating actual values that would be generated by a 
 * Utility Meter.
 * 
 */
#ifndef RandomMeterValue_H
#define RandomMeterValue_H

class RandomMeterValue {

  public:

    // Default constructor
    RandomMeterValue();

    // Public Functions for this class
    int getRandomValue(int maxValue);
    int getRunningValue();
    void setMaxValue(int newMax);
    
  private:

    // Private Variables
    int runningValue;
    int maxRandomValue;
    clock_t this_time;
    clock_t last_time;
    
};

#endif
