matrix:
  include:
    - language: java
      jdk: oraclejdk8
      install: true
      script: true

    - language: node_js
      node_js: 8.9
      addons:
        chrome: stable
      before_install:
        -  # start your web application and listen on `localhost`
        - google-chrome-stable --no-sandbox --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
      install: ./webapp/install-dependencies.sh
      script: ./webapp/test/run-tests.sh
