matrix:
  include:
    - language: java
      jdk: oraclejdk8
      install: true
      script: true

    - language: node_js
      node_js: 8
      install: ./webapp/install-dependencies.sh
      script: ./webapp/test/run-tests.sh
